name: Run CryptoBot

on:
  schedule:
    - cron: '0 */2 * * *'  # Executa a cada 2 horas
  workflow_dispatch:        # Permite executar manualmente também

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          KEY_BINANCE: ${{ secrets.KEY_BINANCE }}
          SECRET_BINANCE: ${{ secrets.SECRET_BINANCE }}
        run: python bot.py
